name: release-CI

on:
  push:
    branches:
    - main

jobs:
  dockerRelease:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: user/poeticpulse-be:latest
            dockerfile: poeticPulse-be/Dockerfile
          - image: user/poeticpulse-ui:latest
            dockerfile: poeticPulse-ui/app1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4                  
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}
