name: release-CI

on:
  push:
    branches:
    - main

jobs:
  build-be:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./poeticPulse-be
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu' 
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

  dockerRelease:
    runs-on: ubuntu-latest
    needs: build-be
    strategy:
      matrix:
        include:
          - image: user/poeticpulse-be:latest
            dockerfile: poeticPulse-be/Dockerfile
          - image: user/poeticpulse-ui:latest
            dockerfile: poeticPulse-ui/Dockerfile
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4                  
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}
