name: release-CI

on:
  push:
    branches:
    - main

jobs:
  dockerRelease:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: user/poeticpulse-be:latest
            dockerfile: poeticPulse-be/Dockerfile
          - image: user/poeticpulse-ui:latest
            dockerfile: poeticPulse-ui/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4                  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu' 
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Checkout poeticPulse-ui sources
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "20.15.0"
      - name: Cache node modules dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install react app dependencies
        run: npm i
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}
